########### Deployment for ActiveMQ (queue)################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb # Deployment name
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template: # template for the pods

    metadata:
      labels:
        app: mongodb # labels apply to the pod
    spec:
      containers:
      - name: mongodb
        image: mongo:3.6.5-jessie
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db # folder inside container we want k8b to mount to a folder
      volumes:                  # Where to store the data for now host machine
        - name: mongo-persistent-storage
          # pointer to the configuration of how we want the mount to be implemented
          persistentVolumeClaim:
            claimName: mongo-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
spec:
  selector:
    app: mongodb
  ports:
    - name: mongoport
      port: 27017
  type: ClusterIP
