# Local storage - mongo-pvc
# What do we want
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: mylocalstorage # Link clam to implementation
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# How do we want it implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/luisdo/Desktop/k8s-course/MicroService-arch # directory on our host system
    type: DirectoryOrCreate
