
########### Deployment for ActiveMQ (queue)################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue # Deployment name
spec:
  selector:
    matchLabels:
      app: queue
  replicas: 1
  template: # template for the pods

    metadata:
      labels:
        app: queue # labels apply to the pod
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release1

---
########## Deployment pod for position simulator############
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator # Deployment name
spec:
  selector:
    matchLabels:
      app: position-simulator
  replicas: 1
  template: # template for the pods

    metadata:
      labels:
        app: position-simulator # labels apply to the pod
    spec:
      containers:
      - name: position-simulator
        image: richardchesterwood/k8s-fleetman-position-simulator:release1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice



---
############ Deployment pod for position tracker#############
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker # Deployment name
spec:
  selector:
    matchLabels:
      app: position-tracker
  replicas: 1
  template: # template for the pods

    metadata:
      labels:
        app: position-tracker # labels apply to the pod
    spec:
      containers:
      - name: position-tracker
        image: richardchesterwood/k8s-fleetman-position-tracker:release1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice

---
########### Deployment pod for api gateway############
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway # Deployment name
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template: # template for the pods

    metadata:
      labels:
        app: api-gateway # labels apply to the pod
    spec:
      containers:
      - name: api-gateway
        image: richardchesterwood/k8s-fleetman-api-gateway:release1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
